# Generated by Django 4.2.5 on 2023-09-28 08:10

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='body',
        ),
        migrations.AddField(
            model_name='file',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='file',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='file',
            name='is_folder',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='file',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='file',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='base.file'),
        ),
        migrations.AddField(
            model_name='file',
            name='title',
            field=models.CharField(default='Untitled', max_length=30),
        ),
    ]
